sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t lukasheinrich/quickana-tutorial .

script:
  - echo 'hello quickana'
  - mkdir results
  - echo "a result" >> results/cutflow.txt
  # - docker run -it lukasheinrich/quickana-tutorial ./tests/travistest.sh
  
after_success: bash deploy.sh